default:
	pdflatex chiel_kooijman.tex
	bibtex chiel_kooijman.aux
	pdflatex chiel_kooijman.tex
	pdflatex chiel_kooijman.tex

clean:
	rm -f chiel_kooijman.aux chiel_kooijman.bbl chiel_kooijman.blg\
		chiel_kooijman.log chiel_kooijman.nav chiel_kooijman.out\
		chiel_kooijman.snm chiel_kooijman.toc
